### ISSUE TITLE
Icon stays after rule is removed.

### ISSUE THREAD

**Issue by bruno-garcia** [joaopgrassi/env-guard#3]
I removed a rule and after refreshing the target page, the title went back to original.
The icon stayed the red icon I had chosen with Env-Guard though. Is it possible to also clear the icon?

I used the StartsWith rule.

The site doesn't have an favicon, perhaps that's why this one doesn't go away.

**Comment by joaopgrassi** [comment]
Steps to reproduce:
1 - create a rule for a page that does not have a favicon on it:
2 - go to the page and refresh it. icon and title should be changed
3 - delete the rule
4 - go back and refresh the page again. Title goes back to normal but favicon remains.

Test site (www.pudim.com.br) Funny and odd site.

**Comment by joaopgrassi** [comment]
Will be available on next release (v.1.0.2)
